// Generated by Wrangler on Mon May 20 2024 10:59:08 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	API_TOKEN: string;
	PROVIDERS: string;
	MAIN_PROVIDER: string;
}
